export enum FoodType {
  LIVE_INSECT = 'LIVE_INSECT',
  FROZEN_PREY = 'FROZEN_PREY',
  PELLET = 'PELLET',
  FRUIT = 'FRUIT',
  VEGETABLE = 'VEGETABLE',
  SUPPLEMENT = 'SUPPLEMENT',
  OTHER = 'OTHER',
}
