export enum LogType {
  FEEDING = 'FEEDING',
  SHEDDING = 'SHEDDING',
  DEFECATION = 'DEFECATION',
  MATING = 'MATING',
  EGG_LAYING = 'EGG_LAYING',
  CANDLING = 'CANDLING',
  HATCHING = 'HATCHING',
}
